"use client"

import React, { createContext, useContext, useMemo, useState } from "react"

type Locale = "pl" | "en" | "de" | "cs" | "sk" | "uk"

type Dict = Record<string, string>

const dictionaries: Record<Locale, Dict> = {
  pl: {
    home: "Dom",
    amenities: "Udogodnienia",
    location: "Lokalizacja",
    gallery: "Galeria",
    contact: "Kontakt",
    amenitiesSubtitle: "Wszystko, czego potrzebujesz na wyjazd",
    locationTitle: "Szczyrk – blisko stoków i szlaków",
    locationDescription: "Centrum Szczyrku, spokojna okolica, blisko restauracji i sklepów.\nSkrzyczne 850 m, SMR 2,8 km, Beskid Sport Arena 2,2 km, SKIBUS 200 m.",
    askAvailability: "Zapytaj o dostępność",
    sauna: "Sauna",
    saunaDesc: "Duża sauna bez dodatkowych opłat",
    salon: "Salon i kuchnia",
    salonDesc: "75'' TV, Netflix, w pełni wyposażona kuchnia",
    terrace: "Taras i grill",
    terraceDesc: "Przestronny taras z grillem gazowym",
    skiroom: "Narciarnia",
    skiroomDesc: "Przechowywanie sprzętu i suszarka do butów",
    contactTitle: "Kontakt",
    contactSubtitle: "Zapytaj o dostępność i wycenę pobytu",
    phone: "Telefon",
    email: "Email",
    address: "Adres",
    addressValue: "Szczyrk, centrum",
    checkInDate: "Data przyjazdu",
    checkOutDate: "Data wyjazdu",
    numberOfPeople: "Liczba osób",
    selectPeople: "Wybierz liczbę osób",
    person: "osoba",
    people: "osoby",
    peopleMany: "osób",
    name: "Imię i nazwisko",
    phoneNumber: "Telefon",
    message: "Wiadomość",
    messageOptional: "Wiadomość (opcjonalnie)",
    additionalInfo: "Dodatkowe informacje...",
    sendInquiry: "Wyślij zapytanie",
    sending: "Wysyłanie...",
    formSent: "Formularz został wysłany. Sprawdź swoją skrzynkę pocztową.",
    fillAllFields: "Proszę wypełnić wszystkie wymagane pola",
    formError: "Wystąpił błąd podczas wysyłania formularza. Spróbuj ponownie.",
    invalidEmail: "Proszę podać poprawny adres email",
    testimonial1: "Świetne miejsce, idealna lokalizacja i bardzo czysto.",
    testimonial2: "Bardzo pomocny kontakt, wszystko zgodnie z opisem.",
    testimonial3: "Sauna i taras to ogromny plus. Polecam!",
    testimonial4: "Piękne widoki, blisko stoków. Na pewno wrócimy.",
    testimonial5: "Dom przestronny i komfortowy, wszystko na plus.",
    testimonial6: "Cicha okolica, super dla rodziny.",
    testimonial7: "Wszystko zgodnie z opisem, polecam.",
    testimonial8: "Świetny kontakt z właścicielem, szybka reakcja.",
    testimonial9: "Bardzo wygodne łóżka i dobrze wyposażona kuchnia.",
    testimonial10: "Idealne miejsce wypadowe na szlaki.",
    carouselHouseOutside: "Dom z zewnątrz",
    carouselSpaciousSalon: "Przestronny salon",
    carouselGuestSauna: "Sauna dla gości",
    carouselMasterBedroom: "Sypialnia główna",
    carouselModernKitchen: "Nowoczesna kuchnia",
    carouselTerraceGrill: "Taras z grillem",
    carouselSeeMore: "Zobacz więcej",
    carouselViewOnMap: "Zobacz na mapie",
    carouselPreviousSlide: "Poprzedni slajd",
    carouselNextSlide: "Następny slajd",
    galleryTitle: "Galeria",
    gallerySubtitle: "Zobacz więcej zdjęć naszego domu i wnętrz",
    googleReviews: "Opinie Google",
  },
  en: {
    home: "Home",
    amenities: "Amenities",
    location: "Location",
    gallery: "Gallery",
    contact: "Contact",
    amenitiesSubtitle: "Everything you need for your stay",
    locationTitle: "Szczyrk – close to slopes and trails",
    locationDescription: "Center of Szczyrk, quiet area, close to restaurants and shops.\nSkrzyczne 850 m, SMR 2.8 km, Beskid Sport Arena 2.2 km, SKIBUS 200 m.",
    askAvailability: "Ask about availability",
    sauna: "Sauna",
    saunaDesc: "Large sauna at no extra charge",
    salon: "Living room and kitchen",
    salonDesc: "75'' TV, Netflix, fully equipped kitchen",
    terrace: "Terrace and grill",
    terraceDesc: "Spacious terrace with gas grill",
    skiroom: "Ski room",
    skiroomDesc: "Equipment storage and boot dryer",
    contactTitle: "Contact",
    contactSubtitle: "Ask about availability and pricing",
    phone: "Phone",
    email: "Email",
    address: "Address",
    addressValue: "Szczyrk, center",
    checkInDate: "Check-in date",
    checkOutDate: "Check-out date",
    numberOfPeople: "Number of people",
    selectPeople: "Select number of people",
    person: "person",
    people: "people",
    peopleMany: "people",
    name: "Full name",
    phoneNumber: "Phone",
    message: "Message",
    messageOptional: "Message (optional)",
    additionalInfo: "Additional information...",
    sendInquiry: "Send inquiry",
    sending: "Sending...",
    formSent: "Form has been sent. Please check your email.",
    fillAllFields: "Please fill in all required fields",
    formError: "An error occurred while sending the form. Please try again.",
    invalidEmail: "Please enter a valid email address",
    testimonial1: "Great place, perfect location and very clean.",
    testimonial2: "Very helpful contact, everything as described.",
    testimonial3: "Sauna and terrace are a huge plus. I recommend!",
    testimonial4: "Beautiful views, close to slopes. We'll definitely come back.",
    testimonial5: "Spacious and comfortable house, everything is a plus.",
    testimonial6: "Quiet area, great for families.",
    testimonial7: "Everything as described, I recommend.",
    testimonial8: "Great contact with the owner, quick response.",
    testimonial9: "Very comfortable beds and well-equipped kitchen.",
    testimonial10: "Perfect base for hiking trails.",
    carouselHouseOutside: "House from outside",
    carouselSpaciousSalon: "Spacious living room",
    carouselGuestSauna: "Guest sauna",
    carouselMasterBedroom: "Master bedroom",
    carouselModernKitchen: "Modern kitchen",
    carouselTerraceGrill: "Terrace with grill",
    carouselSeeMore: "See more",
    carouselViewOnMap: "View on map",
    carouselPreviousSlide: "Previous slide",
    carouselNextSlide: "Next slide",
    galleryTitle: "Gallery",
    gallerySubtitle: "See more photos of our house and interiors",
    googleReviews: "Google Reviews",
  },
  de: {
    home: "Start",
    amenities: "Ausstattung",
    location: "Lage",
    gallery: "Galerie",
    contact: "Kontakt",
    amenitiesSubtitle: "Alles, was Sie für Ihren Aufenthalt brauchen",
    locationTitle: "Szczyrk – nah an Pisten und Wanderwegen",
    locationDescription: "Zentrum von Szczyrk, ruhige Gegend, nah an Restaurants und Geschäften.\nSkrzyczne 850 m, SMR 2,8 km, Beskid Sport Arena 2,2 km, SKIBUS 200 m.",
    askAvailability: "Verfügbarkeit anfragen",
    sauna: "Sauna",
    saunaDesc: "Große Sauna ohne Aufpreis",
    salon: "Wohnzimmer und Küche",
    salonDesc: "75'' TV, Netflix, voll ausgestattete Küche",
    terrace: "Terrasse und Grill",
    terraceDesc: "Geräumige Terrasse mit Gasgrill",
    skiroom: "Skiraum",
    skiroomDesc: "Ausrüstungslager und Stiefeltrockner",
    contactTitle: "Kontakt",
    contactSubtitle: "Verfügbarkeit und Preise erfragen",
    phone: "Telefon",
    email: "E-Mail",
    address: "Adresse",
    addressValue: "Szczyrk, Zentrum",
    checkInDate: "Anreisedatum",
    checkOutDate: "Abreisedatum",
    numberOfPeople: "Anzahl der Personen",
    selectPeople: "Anzahl der Personen auswählen",
    person: "Person",
    people: "Personen",
    peopleMany: "Personen",
    name: "Vollständiger Name",
    phoneNumber: "Telefon",
    message: "Nachricht",
    messageOptional: "Nachricht (optional)",
    additionalInfo: "Zusätzliche Informationen...",
    sendInquiry: "Anfrage senden",
    sending: "Wird gesendet...",
    formSent: "Formular wurde gesendet. Bitte überprüfen Sie Ihr E-Mail-Postfach.",
    fillAllFields: "Bitte füllen Sie alle erforderlichen Felder aus",
    formError: "Beim Senden des Formulars ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.",
    invalidEmail: "Bitte geben Sie eine gültige E-Mail-Adresse ein",
    testimonial1: "Toller Ort, perfekte Lage und sehr sauber.",
    testimonial2: "Sehr hilfreicher Kontakt, alles wie beschrieben.",
    testimonial3: "Sauna und Terrasse sind ein riesiger Pluspunkt. Empfehle ich!",
    testimonial4: "Schöne Aussicht, nah an den Pisten. Wir kommen definitiv wieder.",
    testimonial5: "Geräumiges und komfortables Haus, alles ist ein Plus.",
    testimonial6: "Ruhige Gegend, super für Familien.",
    testimonial7: "Alles wie beschrieben, empfehle ich.",
    testimonial8: "Toller Kontakt mit dem Besitzer, schnelle Reaktion.",
    testimonial9: "Sehr bequeme Betten und gut ausgestattete Küche.",
    testimonial10: "Perfekter Ausgangspunkt für Wanderwege.",
    carouselHouseOutside: "Haus von außen",
    carouselSpaciousSalon: "Geräumiges Wohnzimmer",
    carouselGuestSauna: "Gästesauna",
    carouselMasterBedroom: "Hauptschlafzimmer",
    carouselModernKitchen: "Moderne Küche",
    carouselTerraceGrill: "Terrasse mit Grill",
    carouselSeeMore: "Mehr sehen",
    carouselViewOnMap: "Auf Karte anzeigen",
    carouselPreviousSlide: "Vorherige Folie",
    carouselNextSlide: "Nächste Folie",
    galleryTitle: "Galerie",
    gallerySubtitle: "Sehen Sie weitere Fotos unseres Hauses und der Innenräume",
    googleReviews: "Google Bewertungen",
  },
  cs: {
    home: "Domů",
    amenities: "Vybavení",
    location: "Lokalita",
    gallery: "Galerie",
    contact: "Kontakt",
    amenitiesSubtitle: "Vše, co potřebujete k pobytu",
    locationTitle: "Szczyrk – blízko sjezdovek a stezek",
    locationDescription: "Centrum Szczyrku, klidná oblast, blízko restaurací a obchodů.\nSkrzyczne 850 m, SMR 2,8 km, Beskid Sport Arena 2,2 km, SKIBUS 200 m.",
    askAvailability: "Zeptejte se na dostupnost",
    sauna: "Sauna",
    saunaDesc: "Velká sauna bez příplatku",
    salon: "Obývací pokoj a kuchyň",
    salonDesc: "75'' TV, Netflix, plně vybavená kuchyň",
    terrace: "Terasa a gril",
    terraceDesc: "Prostorná terasa s plynovým grilem",
    skiroom: "Lyžařská místnost",
    skiroomDesc: "Skladování vybavení a sušička bot",
    contactTitle: "Kontakt",
    contactSubtitle: "Zeptejte se na dostupnost a ceny",
    phone: "Telefon",
    email: "E-mail",
    address: "Adresa",
    addressValue: "Szczyrk, centrum",
    checkInDate: "Datum příjezdu",
    checkOutDate: "Datum odjezdu",
    numberOfPeople: "Počet osob",
    selectPeople: "Vyberte počet osob",
    person: "osoba",
    people: "osoby",
    peopleMany: "osob",
    name: "Jméno a příjmení",
    phoneNumber: "Telefon",
    message: "Zpráva",
    messageOptional: "Zpráva (volitelné)",
    additionalInfo: "Další informace...",
    sendInquiry: "Odeslat dotaz",
    sending: "Odesílání...",
    formSent: "Formulář byl odeslán. Zkontrolujte prosím svou e-mailovou schránku.",
    fillAllFields: "Prosím vyplňte všechna povinná pole",
    formError: "Při odesílání formuláře došlo k chybě. Zkuste to prosím znovu.",
    invalidEmail: "Prosím zadejte platnou e-mailovou adresu",
    testimonial1: "Skvělé místo, ideální poloha a velmi čisto.",
    testimonial2: "Velmi užitečný kontakt, vše podle popisu.",
    testimonial3: "Sauna a terasa jsou obrovské plus. Doporučuji!",
    testimonial4: "Krásné výhledy, blízko sjezdovek. Určitě se vrátíme.",
    testimonial5: "Prostorný a pohodlný dům, vše je plus.",
    testimonial6: "Tichá oblast, skvělé pro rodiny.",
    testimonial7: "Vše podle popisu, doporučuji.",
    testimonial8: "Skvělý kontakt s majitelem, rychlá reakce.",
    testimonial9: "Velmi pohodlné postele a dobře vybavená kuchyň.",
    testimonial10: "Ideální výchozí bod pro turistické stezky.",
    carouselHouseOutside: "Dům zvenku",
    carouselSpaciousSalon: "Prostorný obývací pokoj",
    carouselGuestSauna: "Sauna pro hosty",
    carouselMasterBedroom: "Hlavní ložnice",
    carouselModernKitchen: "Moderní kuchyň",
    carouselTerraceGrill: "Terasa s grilem",
    carouselSeeMore: "Více informací",
    carouselViewOnMap: "Zobrazit na mapě",
    carouselPreviousSlide: "Předchozí snímek",
    carouselNextSlide: "Další snímek",
    galleryTitle: "Galerie",
    gallerySubtitle: "Podívejte se na další fotografie našeho domu a interiérů",
    googleReviews: "Google Recenze",
  },
  sk: {
    home: "Domov",
    amenities: "Vybavenie",
    location: "Lokalita",
    gallery: "Galéria",
    contact: "Kontakt",
    amenitiesSubtitle: "Všetko, čo potrebujete na pobyt",
    locationTitle: "Szczyrk – blízko svahov a chodníkov",
    locationDescription: "Centrum Szczyrku, pokojná oblasť, blízko reštaurácií a obchodov.\nSkrzyczne 850 m, SMR 2,8 km, Beskid Sport Arena 2,2 km, SKIBUS 200 m.",
    askAvailability: "Opýtajte sa na dostupnosť",
    sauna: "Sauna",
    saunaDesc: "Veľká sauna bez príplatku",
    salon: "Obývacia izba a kuchyňa",
    salonDesc: "75'' TV, Netflix, plne vybavená kuchyňa",
    terrace: "Terasa a gril",
    terraceDesc: "Priestorná terasa s plynovým grilom",
    skiroom: "Lyžiarska miestnosť",
    skiroomDesc: "Skladovanie vybavenia a sušička topánok",
    contactTitle: "Kontakt",
    contactSubtitle: "Opýtajte sa na dostupnosť a ceny",
    phone: "Telefón",
    email: "E-mail",
    address: "Adresa",
    addressValue: "Szczyrk, centrum",
    checkInDate: "Dátum príchodu",
    checkOutDate: "Dátum odchodu",
    numberOfPeople: "Počet osôb",
    selectPeople: "Vyberte počet osôb",
    person: "osoba",
    people: "osoby",
    peopleMany: "osôb",
    name: "Meno a priezvisko",
    phoneNumber: "Telefón",
    message: "Správa",
    messageOptional: "Správa (voliteľné)",
    additionalInfo: "Ďalšie informácie...",
    sendInquiry: "Odoslať dotaz",
    sending: "Odosielanie...",
    formSent: "Formulár bol odoslaný. Skontrolujte prosím svoju e-mailovú schránku.",
    fillAllFields: "Prosím vyplňte všetky povinné polia",
    formError: "Pri odosielaní formulára došlo k chybe. Skúste to prosím znovu.",
    invalidEmail: "Prosím zadajte platnú e-mailovú adresu",
    testimonial1: "Skvelé miesto, ideálna poloha a veľmi čisto.",
    testimonial2: "Veľmi užitočný kontakt, všetko podľa popisu.",
    testimonial3: "Sauna a terasa sú obrovské plus. Odporúčam!",
    testimonial4: "Krásne výhľady, blízko zjazdoviek. Určite sa vrátime.",
    testimonial5: "Priestorný a pohodlný dom, všetko je plus.",
    testimonial6: "Tichá oblasť, skvelé pre rodiny.",
    testimonial7: "Všetko podľa popisu, odporúčam.",
    testimonial8: "Skvelý kontakt s majiteľom, rýchla reakcia.",
    testimonial9: "Veľmi pohodlné postele a dobre vybavená kuchyňa.",
    testimonial10: "Ideálny východiskový bod pre turistické chodníky.",
    carouselHouseOutside: "Dom zvonka",
    carouselSpaciousSalon: "Priestorná obývačka",
    carouselGuestSauna: "Sauna pre hostí",
    carouselMasterBedroom: "Hlavná spálňa",
    carouselModernKitchen: "Moderná kuchyňa",
    carouselTerraceGrill: "Terasa s grilom",
    carouselSeeMore: "Viac informácií",
    carouselViewOnMap: "Zobraziť na mape",
    carouselPreviousSlide: "Predchádzajúci snímok",
    carouselNextSlide: "Ďalší snímok",
    galleryTitle: "Galéria",
    gallerySubtitle: "Pozrite si viac fotografií nášho domu a interiérov",
    googleReviews: "Google Recenzie",
  },
  uk: {
    home: "Дім",
    amenities: "Зручності",
    location: "Локація",
    gallery: "Галерея",
    contact: "Контакт",
    amenitiesSubtitle: "Все, що потрібно для вашого перебування",
    locationTitle: "Щирик – близько до схилів та стежок",
    locationDescription: "Центр Щирика, тиха місцевість, близько до ресторанів та магазинів.\nСкшичне 850 м, СМР 2,8 км, Бескид Спорт Арена 2,2 км, СКІБАС 200 м.",
    askAvailability: "Запитати про доступність",
    sauna: "Сауна",
    saunaDesc: "Велика сауна без додаткової плати",
    salon: "Вітальня та кухня",
    salonDesc: "75'' ТБ, Netflix, повністю обладнана кухня",
    terrace: "Тераса та гриль",
    terraceDesc: "Простора тераса з газовим грилем",
    skiroom: "Лижна кімната",
    skiroomDesc: "Зберігання спорядження та сушарка для взуття",
    contactTitle: "Контакт",
    contactSubtitle: "Запитайте про доступність та ціни",
    phone: "Телефон",
    email: "Електронна пошта",
    address: "Адреса",
    addressValue: "Щирик, центр",
    checkInDate: "Дата заїзду",
    checkOutDate: "Дата виїзду",
    numberOfPeople: "Кількість осіб",
    selectPeople: "Виберіть кількість осіб",
    person: "особа",
    people: "особи",
    peopleMany: "осіб",
    name: "Ім'я та прізвище",
    phoneNumber: "Телефон",
    message: "Повідомлення",
    messageOptional: "Повідомлення (необов'язково)",
    additionalInfo: "Додаткова інформація...",
    sendInquiry: "Відправити запит",
    sending: "Відправлення...",
    formSent: "Форма була відправлена. Будь ласка, перевірте свою електронну пошту.",
    fillAllFields: "Будь ласка, заповніть всі обов'язкові поля",
    formError: "Під час відправки форми сталася помилка. Спробуйте ще раз.",
    invalidEmail: "Будь ласка, введіть дійсну адресу електронної пошти",
    testimonial1: "Чудове місце, ідеальне розташування і дуже чисто.",
    testimonial2: "Дуже корисний контакт, все як описано.",
    testimonial3: "Сауна і тераса - це величезний плюс. Рекомендую!",
    testimonial4: "Красиві види, близько до схилів. Ми точно повернемося.",
    testimonial5: "Просторий і зручний будинок, все в плюс.",
    testimonial6: "Тиха місцевість, чудово для сімей.",
    testimonial7: "Все як описано, рекомендую.",
    testimonial8: "Чудовий контакт з власником, швидка реакція.",
    testimonial9: "Дуже зручні ліжка і добре обладнана кухня.",
    testimonial10: "Ідеальна база для туристичних стежок.",
    carouselHouseOutside: "Будинок ззовні",
    carouselSpaciousSalon: "Простора вітальня",
    carouselGuestSauna: "Сауна для гостей",
    carouselMasterBedroom: "Головна спальня",
    carouselModernKitchen: "Сучасна кухня",
    carouselTerraceGrill: "Тераса з грилем",
    carouselSeeMore: "Детальніше",
    carouselViewOnMap: "Переглянути на карті",
    carouselPreviousSlide: "Попередній слайд",
    carouselNextSlide: "Наступний слайд",
    galleryTitle: "Галерея",
    gallerySubtitle: "Перегляньте більше фотографій нашого будинку та інтер'єрів",
    googleReviews: "Відгуки Google",
  },
}

type I18nContextValue = {
  locale: Locale
  setLocale: (l: Locale) => void
  t: (key: keyof Dict) => string
}

const I18nContext = createContext<I18nContextValue | null>(null)

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState<Locale>("pl")
  const value = useMemo<I18nContextValue>(() => ({
    locale,
    setLocale,
    t: (key) => dictionaries[locale][key] ?? String(key),
  }), [locale])

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n() {
  const ctx = useContext(I18nContext)
  if (!ctx) throw new Error("useI18n must be used within I18nProvider")
  return ctx
}

export const locales: { code: Locale; label: string }[] = [
  { code: "pl", label: "PL" },
  { code: "en", label: "EN" },
  { code: "de", label: "DE" },
  { code: "cs", label: "CS" },
  { code: "sk", label: "SK" },
  { code: "uk", label: "UK" },
]


